"""verify initial schema

Revision ID: 47731bc68a08
Revises: ce05ed5e490a
Create Date: 2026-08-31 21:32:23.029426
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47731bc68a08'
down_revision: Union[str, None] = 'ce05ed5e490a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
