"""create initial schema

Revision ID: ce05ed5e490a
Revises: 
Create Date: 2026-08-31 20:19:10.709364
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce05ed5e490a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assets',
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('asset_name', sa.String(length=200), nullable=False),
    sa.Column('asset_type', sa.String(length=50), nullable=False),
    sa.Column('asset_subtype', sa.String(length=50), nullable=True),
    sa.Column('symbol', sa.String(length=50), nullable=True),
    sa.Column('currency', sa.CHAR(length=3), nullable=False),
    sa.Column('data_source', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('asset_id')
    )
    op.create_table('fx_rates',
    sa.Column('fx_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('from_currency', sa.CHAR(length=3), nullable=False),
    sa.Column('to_currency', sa.CHAR(length=3), nullable=False),
    sa.Column('exchange_rate', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('rate_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('data_source', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('fx_id'),
    sa.UniqueConstraint('from_currency', 'to_currency', 'rate_timestamp', name='uq_fx_rates_currency_timestamp')
    )
    op.create_table('users',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('user_name', sa.String(length=100), nullable=False),
    sa.Column('pass_hash', sa.String(length=255), nullable=False),
    sa.Column('age', sa.SmallInteger(), nullable=True),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('portfolios',
    sa.Column('portfolio_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('portfolio_name', sa.String(length=100), nullable=False),
    sa.Column('base_currency', sa.CHAR(length=3), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('portfolio_id')
    )
    op.create_index(op.f('ix_portfolios_user_id'), 'portfolios', ['user_id'], unique=False)
    op.create_table('prices',
    sa.Column('price_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('price', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('currency', sa.CHAR(length=3), nullable=False),
    sa.Column('price_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('data_source', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.asset_id'], ),
    sa.PrimaryKeyConstraint('price_id')
    )
    op.create_index(op.f('ix_prices_asset_id'), 'prices', ['asset_id'], unique=False)
    op.create_index(op.f('ix_prices_price_timestamp'), 'prices', ['price_timestamp'], unique=False)
    op.create_table('holdings',
    sa.Column('holding_id', sa.UUID(), nullable=False),
    sa.Column('portfolio_id', sa.UUID(), nullable=False),
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('units', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('avg_buy_price', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('purchase_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.asset_id'], ),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.portfolio_id'], ),
    sa.PrimaryKeyConstraint('holding_id'),
    sa.UniqueConstraint('portfolio_id', 'asset_id', name='uq_holdings_portfolio_asset')
    )
    op.create_index(op.f('ix_holdings_asset_id'), 'holdings', ['asset_id'], unique=False)
    op.create_index(op.f('ix_holdings_portfolio_id'), 'holdings', ['portfolio_id'], unique=False)
    op.create_table('rebalance_events',
    sa.Column('rebalance_id', sa.UUID(), nullable=False),
    sa.Column('portfolio_id', sa.UUID(), nullable=False),
    sa.Column('trigger_type', sa.String(length=30), nullable=False),
    sa.Column('trigger_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('recommended_action', sa.String(length=30), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.portfolio_id'], ),
    sa.PrimaryKeyConstraint('rebalance_id')
    )
    op.create_index(op.f('ix_rebalance_events_portfolio_id'), 'rebalance_events', ['portfolio_id'], unique=False)
    op.create_table('target_allocations',
    sa.Column('target_id', sa.UUID(), nullable=False),
    sa.Column('portfolio_id', sa.UUID(), nullable=False),
    sa.Column('asset_type', sa.String(length=50), nullable=False),
    sa.Column('target_percentage', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.portfolio_id'], ),
    sa.PrimaryKeyConstraint('target_id'),
    sa.UniqueConstraint('portfolio_id', 'asset_type', name='uq_target_allocations_portfolio_asset_type')
    )
    op.create_index(op.f('ix_target_allocations_portfolio_id'), 'target_allocations', ['portfolio_id'], unique=False)
    op.create_table('transactions',
    sa.Column('transaction_id', sa.UUID(), nullable=False),
    sa.Column('portfolio_id', sa.UUID(), nullable=False),
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('transaction_type', sa.String(length=20), nullable=False),
    sa.Column('units', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('price', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('transaction_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fees', sa.Numeric(precision=15, scale=2), server_default='0', nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.asset_id'], ),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.portfolio_id'], ),
    sa.PrimaryKeyConstraint('transaction_id')
    )
    op.create_index(op.f('ix_transactions_asset_id'), 'transactions', ['asset_id'], unique=False)
    op.create_index(op.f('ix_transactions_portfolio_id'), 'transactions', ['portfolio_id'], unique=False)
    op.create_index(op.f('ix_transactions_transaction_date'), 'transactions', ['transaction_date'], unique=False)
    op.create_table('rebalance_actions',
    sa.Column('action_id', sa.UUID(), nullable=False),
    sa.Column('rebalance_id', sa.UUID(), nullable=False),
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('current_allocation', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('target_allocation', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('recommended_value', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.asset_id'], ),
    sa.ForeignKeyConstraint(['rebalance_id'], ['rebalance_events.rebalance_id'], ),
    sa.PrimaryKeyConstraint('action_id')
    )
    op.create_index(op.f('ix_rebalance_actions_asset_id'), 'rebalance_actions', ['asset_id'], unique=False)
    op.create_index(op.f('ix_rebalance_actions_rebalance_id'), 'rebalance_actions', ['rebalance_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rebalance_actions_rebalance_id'), table_name='rebalance_actions')
    op.drop_index(op.f('ix_rebalance_actions_asset_id'), table_name='rebalance_actions')
    op.drop_table('rebalance_actions')
    op.drop_index(op.f('ix_transactions_transaction_date'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_portfolio_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_asset_id'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_target_allocations_portfolio_id'), table_name='target_allocations')
    op.drop_table('target_allocations')
    op.drop_index(op.f('ix_rebalance_events_portfolio_id'), table_name='rebalance_events')
    op.drop_table('rebalance_events')
    op.drop_index(op.f('ix_holdings_portfolio_id'), table_name='holdings')
    op.drop_index(op.f('ix_holdings_asset_id'), table_name='holdings')
    op.drop_table('holdings')
    op.drop_index(op.f('ix_prices_price_timestamp'), table_name='prices')
    op.drop_index(op.f('ix_prices_asset_id'), table_name='prices')
    op.drop_table('prices')
    op.drop_index(op.f('ix_portfolios_user_id'), table_name='portfolios')
    op.drop_table('portfolios')
    op.drop_table('users')
    op.drop_table('fx_rates')
    op.drop_table('assets')
    # ### end Alembic commands ###
